name = "SRDFilter"
uuid = "8500e8d5-1f20-45da-94c5-1be0b4131781"
authors = ["Guido Kraemer <guido.kraemer@uni-leipzig.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[targets]
test = ["Test", "CSV", "DataFrames"]
